version: '3.8'

services:
  backend:
    build: ./backend
    container_name: knowledge-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/knowledgehub
      - JWT_SECRET=your_jwt_secret
      - OPENAI_API_KEY=your_openai_key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: knowledge-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: knowledge-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
